name: domination
version: 1.0.0
author: stecool
main: com.github.steven.domination.Domination
api-version: 1.12.2
commands:
  domination:
    description: start, stop or reload the whole the domination event
    usage: /domination [start,stop,reload]
permissions:
  domination.commands.domination:
    description: Let you use the domination command
  domination.commands.reload:
    description: Let you use the domination command